name: "Publish Release"

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'ubuntu-latest' && 'aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android' || '' }}

      - name: install frontend dependencies
        run: npm install --no-package-lock

      - name: setup Android SDK
        if: matrix.platform == 'ubuntu-latest'
        uses: android-actions/setup-android@v3

      - name: install NDK
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sdkmanager "ndk;26.1.10909125"
          echo "NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_ENV

      - name: init android on CI
        if: matrix.platform == 'ubuntu-latest'
        run: echo "y" | npx tauri android init

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # إضافة المتغيرات دي عشان Rust يشوف الـ NDK Linker صح
          CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER: aarch64-linux-android24-clang
          PATH: ${{ matrix.platform == 'ubuntu-latest' && format('{0}/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin:{1}', env.ANDROID_HOME, env.PATH) || env.PATH }}
        with:
          tagName: v1.0.0
          releaseName: "App v1.0.0"
          releaseBody: "Windows, macOS, and Android (Experimental) versions."
          releaseDraft: false
          prerelease: false
          allowUpdates: true
          args: ${{ matrix.platform == 'ubuntu-latest' && '--target aarch64-linux-android' || '' }}